# Generated by Django 4.0.4 on 2022-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField()),
                ('nombre', models.TextField()),
                ('poderes', models.TextField()),
                ('origen', models.TextField()),
            ],
        ),
    ]
